/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal'
export namespace Components {
  interface MyComponent {
    /**
     * The first name
     */
    first: string
    /**
     * The last name
     */
    last: string
    /**
     * The middle name
     */
    middle: string
  }
  interface OtherComponent {}
}
declare global {
  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement
    new (): HTMLMyComponentElement
  }
  interface HTMLOtherComponentElement extends Components.OtherComponent, HTMLStencilElement {}
  var HTMLOtherComponentElement: {
    prototype: HTMLOtherComponentElement
    new (): HTMLOtherComponentElement
  }
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'other-component': HTMLOtherComponentElement
  }
}
declare namespace LocalJSX {
  interface MyComponent {
    /**
     * The first name
     */
    first?: string
    /**
     * The last name
     */
    last?: string
    /**
     * The middle name
     */
    middle?: string
  }
  interface OtherComponent {}
  interface IntrinsicElements {
    'my-component': MyComponent
    'other-component': OtherComponent
  }
}
export { LocalJSX as JSX }
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>
      'other-component': LocalJSX.OtherComponent & JSXBase.HTMLAttributes<HTMLOtherComponentElement>
    }
  }
}
